# Generated by Django 4.0.6 on 2022-08-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pin_code',
            field=models.CharField(max_length=150),
        ),
    ]
